name: Deploy Calci to Netlify

on:
  push:
    branches: [master, main]
    paths:
      - 'calci/**'
  pull_request:
    branches: [master, main]
    paths:
      - 'calci/**'

jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup:
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install && npm run build
        working-directory: calci  # Ensure this runs in the calci directory

  deploy:
    runs-on: ubuntu-22.04
    needs: setup 
    steps:
      - name: Deploy to Netlify
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_CALCI_BUILD_HOOK }}
