name: Deploy Calci to Netlify

env:
  PROJECT_NAME: 'calci'
  
on:
  push:
    branches: [master, main]
    paths:
      - '{{env.PROJECT_NAME}}/**' # change this for other workflows
      - '.github/workflows/deploy_{{env.PROJECT_NAME}}.yml' # change this for other workflows
  pull_request:
    branches: [master, main]
    paths:
      - '{{env.PROJECT_NAME}}/**' # change this for other workflows
      - '.github/workflows/deploy_{{env.PROJECT_NAME}}.yml' # change this for other workflows

jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup:
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install && npm run build
        working-directory: calci  # Ensure this runs in the calci directory

  deploy:
    runs-on: ubuntu-22.04
    needs: setup 
    steps:
      - name: Deploy to Netlify
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_CALCI_BUILD_HOOK }}
