# .github/workflows/netlify.yml
name: Deploy Calci to Netlify
on:
  push:
    branches: [master, main]
  pull_request: 
    branches: [master, main]
jobs:
  job1:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: calci
    steps:
      - name: Setup working directory
        uses: actions/checkout@v4
      
      - name: List folders
        run: ls

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install && npm run build

      - name: List folders
        run: ls && pwd

      # ( Build to ./dist or other directory... )
      - name: Deploy to Netlify
        # uses: nwtgck/actions-netlify@v3.0
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_CALCI_BUILD_HOOK }}

        # with:
        #   publish-dir: './calci/dist'
        #   production-branch: master
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   deploy-message: "Deploy from GitHub Actions"
        #   enable-pull-request-comment: false
        #   enable-commit-comment: true
        #   overwrites-pull-request-comment: true
        # env:
        #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # timeout-minutes: 1
