name: Deploy Calci to Netlify
on:
  push:
    branches: [master, main]
    paths:
      - 'calci/**'
  pull_request: 
    branches: [master, main]
    paths:
      - 'calci/**'
jobs:
  job1:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: calci
    steps:
      - name: Setup working directory
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install && npm run build

      - name: Deploy to Netlify
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_CALCI_BUILD_HOOK }}
